<div class="modal-container modal-container-hiden" id="modal">
    <div class="modal">
        <a href=""><i class="fa fa-times close"></i></a>
        <h4 class="mb-4"><?php $LANGMNG->echo('t_createAutomation')?></h4>
        <form method="post"  action="" >
            <div class="field">
                <div class="label"><?php $LANGMNG->echo('l_nameAt')?></div>
                <div class="field">
                    <input class="input" type="text" name="name" required/>
                </div>

                <div class="label"><?php $LANGMNG->echo('l_runCondition')?></div>
                <select class="input" name="condOper" id="valueSelector" required>
                    <option	value="or"><?php $LANGMNG->echo('l_oneNeedToBeWaild')?></option>
                    <option	value="and"><?php $LANGMNG->echo('l_allNeedToBeWalid')?></option>
                </select>
                <input type="button" class="button" name="addCondition" value="<?php $LANGMNG->echo('b_add')?>"/>


                <div class="label"><?php $LANGMNG->echo('l_runTask')?></div>
                <input type="button" class="button" name="addTask" value="<?php $LANGMNG->echo('b_add')?>"/>

                <div class="label"><?php $LANGMNG->echo('l_activeTime')?></div>
                <select class="input" name="condOper" id="valueSelector" required>
                    <option	value="allday"><?php $LANGMNG->echo('l_all')?></option>
                    <option	value="daytime"><?php $LANGMNG->echo('l_day')?></option>
                    <option	value="night"><?php $LANGMNG->echo('l_night')?></option>
                    <option	value="custom"><?php $LANGMNG->echo('l_custome')?></option>
                </select>

            </div>
            <input type="submit" class="button" name="modalNext" value="<?php $LANGMNG->echo('b_next')?>"/>
        </form>
    </div>
</div>
