<div class="modal-container">
    <div class="modal">
        <h4 class="mb-4">Login</h4>
        <form method="post">
            <div class="field">
                <div class="label">Name:</div>
                <input class="input" type="text" name="username" placeholder="Jméno.."/>
            </div>
            <div class="field">
                <div class="label">Password:</div>
                <input class="input" type="password" name="password" placeholder="Heslo.."/>
            </div>
            <div class="field">
                <div class="label">Remember me:</div>
                <input class="" type="checkbox" name="remember" value="true"/>
            </div>
				<?php if (!empty ($_SESSION['msg'])): ?>
					<label class="message"><?php echo $_SESSION['msg']; ?></label><br/><br/>
					<?php unset ($_SESSION['msg']); ?>
				<?php endif; ?>
            <input type="submit" class="button" name="login" value="Login"/>
        </form>
    </div>
</div>
