<div class="nav">
    <?php
    $menuItems = [
        'fa-wrench' => [
            'slug' => 'setting',
            'lngKey' => 'settings',
            'path' => 'setting',
        ],
        'fa-calendar-o' => [
            'slug' => 'automation',
            'lngKey' => 'automatization',
            'path' => 'automation',
        ],
        'fa-bug' =>[
            'slug' => 'log',
            'lngKey' => 'log',
            'path' => 'log',
        ],
        'fa-server' =>[
            'slug' => 'server',
            'lngKey' => 'server',
            'path' => 'server',
        ],
    ];
    foreach ( $menuItems as $key => $value) {
        ?>
        <div class="nav-item <?php echo ($ITEM == $value ? 'is-active' : ''); ?>">
            <a href="<?php echo $value['path']?>">
                <i class="fa <?php echo $key ?>"></i>
                <span>
                    <?php $LANGMNG->echo('m_'.$value['lngKey']); ?>
                </span>
            </a>
        </div>
    <?php }?>

</div>
