<div class="modal-container">
    <div class="modal">
        <h4 class="mb-4">Login</h4>
        <form method="post">
            <div class="field">
                <div class="label">Name:</div>
                <input class="input" type="text" name="username" placeholder="Jméno.."/>
            </div>
            <div class="field">
                <div class="label">Password:</div>
                <input class="input" type="password" name="password" placeholder="Heslo.."/>
            </div>

				<input type="hidden" name="responseType" value="<?php echo $RESPONSETYPE; ?>"/>
				<input type="hidden" name="redirectUrl" value="<?php echo $REDIRECTURL; ?>"/>
				<input type="hidden" name="clientId" value="<?php echo $CLIENTID; ?>"/>
				<input type="hidden" name="state" value="<?php echo $STATE; ?>"/>

            <input type="submit" class="button" name="login" value="Login"/>
        </form>
    </div>
</div>
