<div class="modal-container">
    <div class="modal">
        <h4 class="mb-4">OTA</h4>
        <form method="post">
            <input type="hidden" name="otaSecret" value="<?php echo $OTA; ?>" autocomplete="off"/>
            <div class="field">
                <div class="label">Code:</div>
					 <?php

					 ?>
                <input class="input" type="text" name="otaCode" placeholder=""/>
            </div>
            <input type="submit" class="button" name="login" value="Login"/>
        </form>
    </div>
</div>
