<div class="col-12 col-md-6 col-xl-4 square-wrap">
	<div class="rectangle-2">
		<div class="square-content double <?php echo ($PLUGINSTATUS == false ? 'is-inactive' : ''); ?>">
			<div class="row">
				<div class="col-1">
					<h5 class="fa">
						<?php echo $PLUGINNAME ?>
					</h5>
				</div>
			</div>
			<div class="row">
				<div class="col">
					<form method="post" action="">
						<input type="hidden" name="name" value="<?php echo $PLUGINNAME; ?>"/>
						<input type="hidden" name="status" value="true"/>
						<a class="button is-primary m-1" onclick="$(this).closest('form').submit();"><?php $LANGMNG->echo('b_approve')?></a>
					</form>
				</div>
				<div class="col">
					<form method="post" action="">
						<input type="hidden" name="name" value="<?php echo $PLUGINNAME; ?>"/>
						<input type="hidden" name="status" value="false"/>
						<a class="button is-primary m-1" onclick="$(this).closest('form').submit();"><?php $LANGMNG->echo('b_disable')?></a>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
