<!DOCTYPE html>
<html lang="en">
<head>
	<?php
	$partial = new Partial('head');
	$partial->prepare('baseDir', $BASEDIR);
	$partial->render();
	?>
	<title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
	<div class="row no-gutters main">
		<div class="col-md-3 d-sm-none"></div>
		<div class="col-md-3 nav-container">
			<?php
			$partial = new Partial('menu');
			$partial->prepare('item', 'device');
			$partial->prepare('langMng', $LANGMNG);
			$partial->prepare('debugMod', $DEBUGMOD);
			$partial->render();
			?>
		</div>
		<div class="col-md-9 main-body">
			<table class="table is-fluid">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Room</th>
						<th>Firmware</th>
						<th>IP Address<br>(Mac)</th>
						<th>Action
							<form method="post" action="">
								<button class="fa custom-file-input" type="submit" name="deviceCommand" value="reset" title="Reset All"><b>&#xf01e;</b></button>
								<div style="float: clear;"></div>
							</form>
						</th>
					</tr>
				</thead>
				<tbody>
					<?php if (!empty($DEVICES)) : ?>
						<?php foreach ($DEVICES as $device) : ?>
							<tr>
								<td><i class="fa">&#x<?php echo (!empty($device['icon']) ? $device['icon'] : ""); ?></i></td>
								<td><?php echo (!empty($device['name']) ? $device['name'] : ""); ?></td>
								<td>
								<select class="input" id="device-<?php echo $device['device_id']?>-roomId">
								<?php
									foreach ($ROOMS as $key => $room) {
										echo '<option value="'.$room['room_id'].'" '.($device['room_id'] == $room['room_id'] ? 'selected' : '').'>'.$room['name'].'</option>';
									}
								?>
								</select>
								</td>
								<td>
									<?php if (!empty($device['mac'])) : ?>
										<?php 
										$icon = "fa-circle";
										$color = "yellow";
										if (!empty($device['firmware_hash'])) {
											if ($device['firmware_hash'] == "true") {
												$icon = "fa-check-circle";
												$color = "green";
											} else if ($device['firmware_hash'] == "need") {
												$icon = "arrow-circle-up";
											} else {
												$icon = "fa-times-circle";
												$color = "red";
											}
										}
										?>
										
										<i class="fa <?php echo $icon; ?>" style="color: <?php echo $color; ?>"></i>
										<?php echo $device['firmware_hash'] ?>
										<button class="fa custom-file-input" type="button" onclick="document.getElementById('deviceFirmware-<?php echo $device['device_id']?>').click();">&#xf0ee;</button>
										<form style="display: none;" method="post" action="" enctype="multipart/form-data">
											<input type="hidden" name="deviceId" value="<?php echo (!empty($device['device_id']) ? $device['device_id'] : ""); ?>">
											<input type="file" onchange="this.form.submit();" name="deviceFirmware" id="deviceFirmware-<?php echo $device['device_id']?>" value="">
										</form>
									<?php endif; ?>
									<div type="float: clear;"></div>
								</td>
								<td><?php echo (!empty($device['mac']) ? $device['mac'] : ""); ?><br><?php echo (!empty($device['ip_address']) ? $device['ip_address'] : ""); ?></td>
								<td>
									<?php if (!empty($device['mac'])) : ?>
										<form method="post" action="">
											<input type="hidden" name="deviceId" value="<?php echo (!empty($device['device_id']) ? $device['device_id'] : ""); ?>">
											<button class="fa custom-file-input" <?php echo (!empty($device['command']) && $device['command'] == "reset" ? "style=\"color:red;\"" : ""); ?> type="submit" name="deviceCommand" value="reset" title="Reset">&#xf01e;</button>
											<button class="fa custom-file-input" <?php echo (!empty($device['command']) && $device['command'] == "config" ? "style=\"color:red;\"" : ""); ?> type="submit" name="deviceCommand" value="config" title="Config">&#xf013;</button>
											<div style="float: clear;"></div>
										</form>
									<?php endif; ?>
								</td>
							</tr>
						<?php endforeach; ?>
					<?php endif; ?>
				<tbody>
			</table>
		</div>

		<?php
		$partial = new Partial('footer');
		$partial->prepare('baseDir', BASEDIR);
		$partial->render();
		//TODO js do main.js
		?>
</body>

</html>
