<!DOCTYPE html>
<html lang="en">
<head>
	<?php
	$partial = new Partial('head');
	$partial->prepare('baseDir', $BASEDIR);
	$partial->render();
	?>
	<title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
	<div class="row no-gutters main">
		<div class="col-md-3 d-sm-none"></div>
		<div class="col-md-3 nav-container">
			<?php
			$partial = new Partial('menu');
			$partial->prepare('item', 'device');
			$partial->prepare('langMng',$LANGMNG);
			$partial->prepare('debugMod',$DEBUGMOD);
			$partial->render();
			?>
		</div>
		<div class="col-md-9 main-body">
			<table>
				<thead>
					<tr>
						<th>Icon</th>
						<th>Name</th>
						<th>Firmware</th>
						<th>Mac</th>
						<th>IP Address</th>
						<th>Action</th>
					</tr>
				</thead>
				<tbody>
					<?php if (!empty ($DEVICES)): ?>
						<?php foreach ($DEVICES as $device): ?>
							<tr>
								<td><i class="fa">&#x<?php echo (!empty ($device['icon']) ? $device['icon'] : ""); ?></i></td>
								<td><?php echo (!empty ($device['name']) ? $device['name'] : ""); ?></td>
								<td>
									<?php if (!empty ($device['mac'])): ?>
										<i
											class="fa <?php echo (!empty ($device['firmware_hash']) ? ($device['firmware_hash'] != "need" ? "fa-check-circle" : "fa-circle") : "fa-times-circle"); ?>"
											style="float: center; <?php echo (!empty ($device['firmware_hash']) ? ($device['firmware_hash'] != "need" ? "color: green;" : "color: yellow;") : "color: red;"); ?>"
										></i>
										<button class="fa custom-file-input" type="button" onclick="document.getElementById('deviceFirmware').click();" >&#xf0ee;</button>
										<form style="display: none;" method="post" action="" enctype="multipart/form-data">
											<input type="hidden" name="deviceId" value="<?php echo (!empty ($device['device_id']) ? $device['device_id'] : ""); ?>">
											<input type="file" onchange="this.form.submit();" name="deviceFirmware" id="deviceFirmware" value="">
										</form>
									<?php endif; ?>
									<div type="float: clear;"></div>
								</td>
								<td><?php echo (!empty ($device['mac']) ? $device['mac'] : ""); ?></td>
								<td><?php echo (!empty ($device['ip_address']) ? $device['ip_address'] : ""); ?></td>
								<td>
									<form method="post" action="">
										<input type="hidden" name="deviceId" value="<?php echo (!empty ($device['device_id']) ? $device['device_id'] : ""); ?>">
										<button class="fa custom-file-input" type="submit" name="deviceCommand" value="reset" title="Reset">&#xf01e;</button>
										<button class="fa custom-file-input" type="submit" name="deviceCommand" value="config" title="Config">&#xf013;</button>
										<div style="float: clear;"></div>
									</form>
								</td>
							</tr>
						<?php endforeach; ?>
					<?php endif; ?>
				<tbody>
			</table>
		</div>

			<?php
			$partial = new Partial('footer');
			$partial->prepare('baseDir', BASEDIR);
			$partial->render();
			//TODO js do main.js
			?>
	</body>
</html>
