<!DOCTYPE html>
<html lang="en">
<head>
	<?php
	$partial = new Partial('head');
	$partial->prepare('baseDir',$BASEDIR);
	$partial->render();
	?>
	<title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
	<?php
	if (isset($ota) && $ota != '') {
		$partial = new Partial('loginOta');
		$partial->prepare('ota',$ota);
		$partial->render();
	} else {
		$partial = new Partial('loginForm');
		$partial->render();
	}
	?>

	<?php
	$partial = new Partial('footer');
	$partial->prepare('baseDir', BASEDIR);
	$partial->render();
	?>
</body>
</html>
