<!DOCTYPE html>
<html lang="en">
<head>
	<?php
	$partial = new Partial('head');
	$partial->prepare('baseDir', $BASEDIR);
	$partial->render();
	?>
	<title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
	<div class="row no-gutters main">
		<div class="col-md-3 d-sm-none"></div>
		<div class="col-md-3 nav-container">
			<?php
			$partial = new Partial('menu');
			$partial->prepare('item', 'plugins');
			$partial->prepare('langMng',$LANGMNG);
			$partial->prepare('debugMod',$DEBUGMOD);
			$partial->render();
			?>
		</div>
		<div class="col-md-9 main-body">
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h1><?php echo $LANGMNG->get('t_Plugins');
				 ?></h1>

				<div class="row mb-4">
					<?php if ($PLUGINS): ?>
						<?php foreach ($PLUGINS as $plugin):

								//BUTTON
								$partial = new Partial('pluginButton');
								$partial->prepare('langMng',$LANGMNG);
								$partial->prepare('pluginName',$plugin['name']);
								$partial->prepare('pluginStatus',$plugin['status']);
								$partial->render();

						?>
						<?php endforeach; ?>
					<?php endif; ?>
				</div>
			</div>
		</div>

		<?php
		$partial = new Partial('footer');
		$partial->prepare('baseDir', BASEDIR);
		$partial->render();
		//TODO js do main.js
		?>
	</body>
	</html>
