<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    $partial = new Partial('head');
	 $partial->prepare('baseDir', $BASEDIR);
	 $partial->prepare('baseUrl', $BASEURL);
    $partial->render();
    ?>
    <title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
    <div class="row no-gutters main">
        <div class="col-md-3 d-sm-none"></div>
        <div class="col-md-3 nav-container">
            <?php
                $partial = new Partial('menu');
                $partial->prepare('item', 'log');
                $partial->prepare('langMng',$LANGMNG);
                $partial->prepare('debugMod',$DEBUGMOD);
                $partial->render();
            ?>
        </div>
        <div class="col-md-9 main-body">
            <div class="col-12 col-sm-9 mx-auto mt-4">
                <h1><?php echo $LANGMNG->get('t_ServerStats'); ?></h1>
                <hr>
                    <label>UPTIME: <?php echo $UPTIME;?></label></br>
                    <label>SERVER TIME: <?php echo $SERVERTIME;?></label></br>
                    <label>SERVER NAME: <?php echo $NAME;?></label></br>
                    <label>SERVER ADDRESS: <?php echo $IP;?></label></br>
                <hr>
                    <label>CPU: <?php echo $CPU;?></label></br>
                    <label>CPU Usage: </label><progress value="<?php echo $CPU;?>" max="100"> <?php echo $RAMFREE;?> </progress></br>
                <hr>
                    <label>RAM TOTAL: <?php echo $RAMTOTAL;?></label></br>
                    <label>RAM FREE: <?php echo $RAMFREE;?></label></br>
                    <label>RAM Usage: </label><progress value="<?php echo explode(" ", $RAMTOTAL)[0] - explode(" ", $RAMFREE)[0];?>" max="<?php echo explode(" ", $RAMTOTAL)[0];?>"> <?php echo $RAMFREE;?> </progress></br>
                <hr>
                    <label>DISK TOTAL: <?php echo $DISKTOTAL;?> bytes</label></br>
                    <label>DISK FREE: <?php echo $DISKFREE;?> bytes</label></br>
                    <label>DISK Usage: </label><progress value="<?php echo explode(" ", $DISKTOTAL)[0] - explode(" ", $DISKFREE)[0];?>" max="<?php echo explode(" ", $DISKTOTAL)[0];?>"> <?php echo $DISKFREE;?> </progress></br>
                <hr>
            </div>
        </div>

        <?php
            $partial = new Partial('footer');
            $partial->prepare('baseDir', BASEDIR);
            $partial->render();
            //TODO js do main.js
        ?>

    </body>
    </html>
