<div class="col-4 col-sm-3 col-xl-2 square-wrap">
    <div class="square">
        <div class="square-content" id="device-<?php echo $DASHBOARDITEMDATA['masterId'] ?>" onClick="ajaxPost('ajax',{subDevice_id:'<?php echo $DASHBOARDITEMDATA['id']; ?>'}, this);">
            <div class="content">
                <div class="row">
                    <div class="col">
                        <h5 class="fa">&#x<?php echo $DASHBOARDITEMDATA['icon'] ?></h5>
                    </div>
                    <div class="col">
                        <h5 class="text-right"><?php echo $DASHBOARDITEMDATA['lastRecord']['value'].''.$DASHBOARDITEMDATA['unit'] ?></h5>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        <?php echo $DASHBOARDITEMDATA['name'] ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>