<?php 
$action = "";
if ($SUBDEVICE['type'] == 'on/off') {
	$action = 'onClick="ajaxPost(\'ajax\',{subDevice_id:\'' . $SUBDEVICEID . '\'}, this);"';
} 
//neaktivní zařízení is-inactive
?>

<div class="device-button col-4 col-sm-3 col-xl-2 square-wrap" <?php echo $action; ?> data-room-id="<?php echo $ROOMID; ?>">
	<div class="square">
		<div class="square-content <?php echo ($SUBDEVICE['comError'] ? "is-inactive" : "") ;?>" id="device-<?php echo $DEVICEID ?>" data-sub-device-id="<?php echo $SUBDEVICEID;?>">
			<div class="content">
				<div class="row">
					<div class="col">
						<h5 unselectable="on" class="fa">&#x<?php echo $DEVICE['icon'] ?></h5>
					</div>
					<div class="col">
						<h5 unselectable="on" class="device-button-value text-right" title="<?php echo $SUBDEVICE['lastRecort']['time']; ?>"><?php echo $SUBDEVICE['lastRecort']['value'] . $SUBDEVICE['unit']?></h5>
					</div>
				</div>
				<div class="row">
					<div class="col" unselectable="on" >
						<?php echo $DEVICE['name']; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
