<?php 
$action = "";
if ($SUBDEVICE['type'] == 'on/off') {
	$action = 'onClick="ajaxPost(\'ajax\',{subDevice_id:\'' . $SUBDEVICEID . '\', action:\'change\'}, this);"';
} 
//neaktivní zařízení is-inactive
?>

<div class="device-button col-4 col-sm-3 col-xl-2 square-wrap" <?php echo $action; ?> data-room-id="<?php echo $ROOMID; ?>">
	<div class="square">
		<div class="square-content <?php echo (($SUBDEVICE['comError'] == 1 || $DEVICE['approved'] == 0) ? "is-inactive" : "") ;?>" id="device-<?php echo $DEVICEID ?>" data-sub-device-id="<?php echo $SUBDEVICEID;?>">
			<div class="content">
				<div class="row no-gutters">
					<div class="col">
						<h5 unselectable="on" class="fa">&#x<?php echo $DEVICE['icon'] ?></h5>
					</div>
					<div class="col">
					<?php if ($SUBDEVICE['type'] == 'temp_cont') { ?>
						<input type="number" step="5" class="device-button-value text-right" id="value_control" value="<?php echo $SUBDEVICE['lastRecort']['value'] ?>"><?php echo $SUBDEVICE['unit']?>
						<style>
							input.device-button-value.text-right {
    							width: inherit;
							}
						</style>
					
					<?php } else { ?>
						<h5 unselectable="on" class="device-button-value text-right" title="<?php echo $SUBDEVICE['lastRecort']['time']; ?>"><?php echo $SUBDEVICE['lastRecort']['value'] . $SUBDEVICE['unit']?></h5>
					<?php } ?>	
					</div>
				</div>
				<div class="row">
					<div class="col  button-text" unselectable="on" >
						<?php echo $DEVICE['name']; ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
