<!-- Detail -->
<div class="modal-container modal-container-hiden" id="modal-detail-<?php echo $SUBDEVICEID;?>">
	<div class="modal">
		<div class="close">
			<i class="fa fa-times"></i>
		</div>
		<h4 class="mb-4"><?php echo $DEVICE['name']; ?></h4>
		<h5 class="mb-4"><?php echo $SUBDEVICE['lastRecort']['value'] . $SUBDEVICE['unit']?></h5>
		<p><?php $LANGMNG->echo('l_lastSeen'); echo ' ' . $SUBDEVICE['lastRecort']['niceTime']; ?></p>
		<div class="">
			<canvas id="canvas-<?php echo $SUBDEVICEID;?>"></canvas>
		</div>
		
		
		<input 
		type="submit" 
		class="button col-2 graph-period" 
		data-period="year" 
		data-group="month"
		data-sub-device-id="<?php echo $SUBDEVICEID;?>"
		value="<?php $LANGMNG->echo('b_year');?>"
		/>	
		
		<input 
		type="submit" 
		class="button col-2  graph-period" 
		data-period="month" 
		data-group="day"
		data-sub-device-id="<?php echo $SUBDEVICEID;?>"  
		value="<?php $LANGMNG->echo('b_month');?>"
		/>	
		
		<input 
		type="submit" 
		class="button col-2 graph-period" 
		data-period="week" 
		data-group="day"
		data-sub-device-id="<?php echo $SUBDEVICEID;?>"
		value="<?php $LANGMNG->echo('b_week');?>"
		/>
		
		<input 
		type="submit" 
		class="button col-2  graph-period" 
		data-period="day" 
		data-group="hour"
		data-sub-device-id="<?php echo $SUBDEVICEID;?>"
		value="<?php $LANGMNG->echo('b_day');?>"
		/>
		
		<input 
		type="submit" 
		class="button col-2  graph-period" 
		data-period="hour" 
		data-group="minute"
		data-sub-device-id="<?php echo $SUBDEVICEID;?>"
		value="<?php $LANGMNG->echo('b_hour');?>"
		/>
		
		<div>
			<table class="table is-fluid">
				<thead>
					<tr>
						<th><?php $LANGMNG->echo('t_time');?></th>
						<th><?php $LANGMNG->echo('t_state');?></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($SUBDEVICE['events'] as $key => $value) { ?>
						<tr>
							<th><?php echo (new DateTime($value['time']))->format(DATEFORMAT); ?></th>
							<th title="test"><?php echo $value['value'] . $SUBDEVICE['unit'];?></th>
							<?php //TODO: P5IDAT TOOLTIP PRO RAW VALUE?>
						</tr>
					<?php } ?>
				</tbody>
			</table>
		</div>
	</div>
</div>