<div class="modal-container modal-container-hiden" id="modal">
    <div class="modal">
        <div class="close">
            <i class="fa fa-times"></i>
        </div>
        <h4 class="mb-4"><?php echo $LANG['t_createScene'];?></h4>
        <form method="post" action="" >
            <div class="field">
                <div class="label"><?php echo $LANG['w_title'];?>:</div>
                <input type="text" class="input" name="sceneName" value=""/>  
            </div>
            <div class="field">
                <div class="label"><?php echo $LANG['w_icon'];?>:</div>
                <select class="input fa" name="sceneIcon" <?php echo (!$DEVICE['userIsAdmin'] ? 'disabled' : ''); ?>>
                    <option value="">No icon</option>
                    <option value="f0eb">&#xf0eb; - fa-lightbulb-o</option>
                    <option value="f2dc">&#xf2dc; - fa-snowflake-o</option>
                    <option value="f0e7">&#xf0e7; - fa-bolt</option>
                    <option value="f2c7">&#xf2c7; - fa-thermometer-full</option>
                    <option value="f236">&#xf236; - fa-bed</option>
                    <option value="f185">&#xf185; - fa-sun-o</option>
                    <option value="f2db">&#xf2db; - fa-microchip</option>
                    <option value="f011">&#xf011; - fa-power-off</option>
                    <option value="f011">&#xf108; - fa-desktop</option>
                </select>
            </div>
            <div class="field">
                <div class="label"><?php echo $LANG['l_choseDevice'];?></div>
                <select  class="input" name="devices[]" multiple>
                    <?php
                    foreach ($SUBDEVICES as $subdeviceId => $subdeviceData) {
                        echo '<option value="'.$subdeviceId.'">'.$subdeviceData['name'].'</option>';
                    }
                    ?>
                </select>
            </div>
            <input type="submit" class="button" name="submit" value="<?php echo $LANG['b_next'];?>"/>
        </form>
    </div>
</div>