<div class="modal-container" id="modal">
    <div class="modal">
        <div class="close">
            <i class="fa fa-times"></i>
        </div>
        <h4 class="mb-4"><?php $LANGMNG->echo('t_createScene');?></h4>
        <form method="post">
            <input type="hidden" name="sceneName" value="<?php echo $SCENENAME; ?>">
            <input type="hidden" name="sceneIcon" value="<?php echo $SCENEICON; ?>">
            <?php 
            $i = 0;
            foreach($SETSTATEFORMDEVICES as $device){ ?>
                <div class="field px-2">
                    <div class="label"><?php echo $device['name']; ?></div>
                    <select  class="input" name="devices[<?php echo $device['setableSubDevices']; ?>]">
                        <option value="0">off</option>
                        <option value="1">on</option>
                    </select>
                </div>
                <?php 
                $i++;
            } ?>
            <input type="submit" class="button" name="submitFinal" value="<?php echo $LANGMNG->echo('b_create');?>"/>
        </form>
    </div>
</div>