<!DOCTYPE html>
<html lang="en">
<head>
	<?php
	$partial = new Partial('head');
	$partial->render();
	?>
	<title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
	<div class="row no-gutters main">
		<div class="col-md-3 d-sm-none"></div>
		<div class="col-md-3 nav-container">
			<div class="nav">
				<div class="nav-item">
					<a href="./"><i class="fa fa-home"></i><span><?php echo $LANG['m_home']?></span></a>
				</div>
				<div class="nav-item">
					<a href="dashboard"><i class="fa fa-tachometer" aria-hidden="true"></i><span><?php echo $LANG['m_dashboard']?></span></a>
				</div>
				<div class="nav-item">
					<a href="setting"><i class="fa fa-wrench" aria-hidden="true"></i></i><span><?php echo $LANG['m_settings']?></span></a>
				</div>
				<div class="nav-item is-active">
					<a href="automation"><i class="fa fa-calendar-o" aria-hidden="true"></i><span><?php echo $LANG['m_automatization']?></span></a>
				</div>
				<div class="nav-item">
					<a href="scene"><i class="fa fa-terminal" aria-hidden="true"></i><span><?php echo $LANG['m_scenes']?></span></a>
				</div>
			</div>
		</div>
		<div class="col-md-9 main-body">
			<a class="button is-primary m-1" onClick="$('#modal').removeClass('modal-container-hiden').show();"><?php echo $LANG['t_createAutomation'];?></a>
			<div class="row no-gutters">
				<?php foreach ($AUTOMATIONS as $automationId => $automationData) {
					//BUTTON
					$partial = new Partial('automationButton');
					$partial->prepare('lang',$LANG);
					$partial->prepare('automationId',$automationId);
					$partial->prepare('automationData',$automationData);
					$partial->render();
					
					//EDIT
					$partial = new Partial('automationEdit');
					$partial->prepare('lang',$LANG);
					$partial->prepare('automationId',$automationId);
					$partial->prepare('automation',$automationData);
					$partial->prepare('subDevices',$SUBDEVICES);
					$partial->render();
				} ?>
			</div>
		</div>
	</div>
	<?php 
	ECHO $_POST['modalNext'];
	if (isset($_POST['modalNext'])) {
		$partial = new Partial('automationCreateFinal');
		$partial->prepare('lang',$LANG);
		$partial->prepare('subDevices',$SUBDEVICES);
		$partial->render();
	} else {
		$partial = new Partial('automationCreate');
		$partial->prepare('lang',$LANG);
		$partial->prepare('subDevices',$SUBDEVICES);
		$partial->render();
	}
	$partial = new Partial('footer');
	$partial->render();
	?>
</body>
</html>
