<!DOCTYPE html>
<html lang="en">
<head>
	<?php
	$partial = new Partial('head');
	$partial->prepare('baseDir', $BASEDIR);
	$partial->render();
	?>
	<title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
	<div class="row no-gutters main">
		<div class="col-md-3 d-sm-none"></div>
		<div class="col-md-3 nav-container">
			<?php
			$partial = new Partial('menu');
			$partial->prepare('item', 'setting');
			$partial->prepare('langMng',$LANGMNG);
			$partial->render();
			?>
		</div>
		<div class="col-md-9 main-body">
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4">	
					<?php $LANGMNG->echo('t_pageAfterLogIn') ?>
				</h4>
				<form method="post" enctype="multipart/form-data">
					<div class="">
						<div class="field">
							<select class="input" name="loadPage">
								<option value="0" <?php echo (UserManager::getUserData("startPage") == 0 ? "selected" : ""); ?>>Default</option>
								<option value="1" <?php echo (UserManager::getUserData("startPage") == 1 ? "selected" : ""); ?>>Dashboard</option>
							</select>
						</div>
						<input type="submit" name="submit" class="button" value="<?php $LANGMNG->echo('b_save') ?>"/>
					</div>
				</div>
			</form>
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4"><?php $LANGMNG->echo('t_profile') ?></h4>
				<div class="field">
					<a href="logout" class="button is-primary"><?php $LANGMNG->echo('b_logOut') ?></a>
				</div>
			</div>
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4"><?php $LANGMNG->echo('t_notification') ?></h4>
				<input id="notifications" type="checkbox" onChange="toggleNotificationPermissions(this);" />
				<div class="label"><?php $LANGMNG->echo('l_notificationStatus') ?></div>
				<div class="field">
					<a onClick="sendTestNotification();" class="button"><?php $LANGMNG->echo('b_sendTestNotification');?></a>
				</div>
			</div>
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4"><?php $LANGMNG->echo('t_experimental') ?></h4>
				<div class="field">
					<a href="rooms" class="button"><?php $LANGMNG->echo('b_rooms') ?></a>
				</div>
			</div>
		</div>
		
		
	</div>
	<script src="./app/templates/js/setting.js"></script>
	<?php
	$partial = new Partial('footer');
	$partial->render();
	?>
	</script>
</body>
</html>
