<!DOCTYPE html>
<html lang="en">
<head>
	<?php
	$partial = new Partial('head');
	$partial->render();
	?>
	<title><?php echo $TITLE ?></title>
</head>
<body class="no-transitions">
	<div class="row no-gutters main">
		<div class="col-md-3 d-sm-none"></div>
		<div class="col-md-3 nav-container">
			<?php
			$partial = new Partial('menu');
			$partial->prepare('item', 'setting');
			$partial->prepare('lang',$LANG);
			$partial->render();
			?>
		</div>
		<div class="col-md-9 main-body">
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4">Stránka po načtení</h4>
				<form method="post" enctype="multipart/form-data">
					<div class="">
						<div class="field">
							<select class="input" name="loadPage">
								<option value="0" <?php echo (UserManager::getUserData("startPage") == 0 ? "selected" : ""); ?>>Default</option>
								<option value="1" <?php echo (UserManager::getUserData("startPage") == 1 ? "selected" : ""); ?>>Dashboard</option>
							</select>
						</div>
						<input type="submit" name="submit" class="button" value="Uložit"/>
					</div>
				</div>
			</form>
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4">Profil</h4>
				<div class="field">
					<a href="logout" class="button is-primary">Odhlásit se</a>
				</div>
			</div>
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4">Notifications</h4>
				<input id="notifications" type="checkbox" onChange="toggleNotificationPermissions(this);" />
				<div class="label">Status notifikací</div>
				<div class="field">
					<a onClick="sendTestNotification();" class="button">Test Notification</a>
				</div>
			</div>
			<div class="col-12 col-sm-9 mx-auto mt-4">
				<h4 class="mb-4">Logs</h4>
				<div class="field">
					<a href="rooms" class="button">ROOMS</a>
				</div>
			</div>
		</div>
		
		
	</div>
	<script src="./app/templates/js/setting.js"></script>
	<?php
	$partial = new Partial('footer');
	$partial->render();
	//TODO js do main.js
	?>
	<script>
	$( "#enable-features" ).click(function(e) {
		var selectRoomId = localStorage.getItem("enableFeature");
		if (selectRoomId){
			localStorage.setItem("enableFeature", true);
		}else {
			localStorage.setItem("enableFeature", false);
		}
	});
	</script>
</body>
</html>
